all:
  hosts:
    my.server.1:
      ansible_ssh_private_key_file: ../terraform/.ssh/my_ssh_key
      ansible_user: ubuntu
      ansible_ssh_host: 3.135.237.149
      ansible_become: true

    my.server.2:
      ansible_ssh_private_key_file: ../terraform/.ssh/my_ssh_key
      ansible_user: ubuntu
      ansible_ssh_host: 3.142.145.79
      ansible_become: true
